import type { ZeroDB } from './main';

import { env as _env } from 'cloudflare:workers';

export type ZeroEnv = {
  ZERO_DB: DurableObjectNamespace<ZeroDB>;
  HYPERDRIVE: { connectionString: string };
  pending_emails_status: KVNamespace;
  pending_emails_payload: KVNamespace;
  scheduled_emails: KVNamespace;
  send_email_queue: Queue;
  snoozed_emails: KVNamespace;
  gmail_sub_age: KVNamespace;
  subscribe_queue: Queue;
  MAIL_INGRESS_QUEUE: Queue;
  MAIL_OUTBOUND_QUEUE: Queue;
  gmail_history_id: KVNamespace;
  gmail_processing_threads: KVNamespace;
  subscribed_accounts: KVNamespace;
  connection_labels: KVNamespace;
  NODE_ENV: 'local' | 'development' | 'production';
  JWT_SECRET: 'secret';
  BASE_URL: string;
  VITE_PUBLIC_APP_URL: string;
  DATABASE_URL: string;
  CREDENTIAL_ENCRYPTION_KEY: string;
  BETTER_AUTH_SECRET: string;
  BETTER_AUTH_URL: string;
  RESEND_API_KEY: string;
  VITE_PUBLIC_POSTHOG_KEY: string;
  VITE_PUBLIC_POSTHOG_HOST: string;
  COOKIE_DOMAIN: string;
  BETTER_AUTH_TRUSTED_ORIGINS: string;
  ZERO_ADMIN_AUTO_PROVISION?: 'true' | 'false';
  ZERO_ADMIN_NAME?: string;
  ZERO_ADMIN_EMAIL?: string;
  ZERO_ADMIN_PASSWORD?: string;
  ZERO_ADMIN_BOOTSTRAP_SECRET?: string;
  GITHUB_CLIENT_ID: string;
  GITHUB_CLIENT_SECRET: string;
  HISTORY_OFFSET: string;
  ZERO_CLIENT_ID: string;
  ZERO_CLIENT_SECRET: string;
  VITE_PUBLIC_BACKEND_URL: string;
  REDIS_URL: string;
  REDIS_TOKEN: string;
  EARLY_ACCESS_ENABLED: string;
  REACT_SCAN: string;
  GOOGLE_S_ACCOUNT: string;
  GMAIL_PUBSUB_TOPIC_NAME: string;
  GMAIL_PUBSUB_SUBSCRIPTION_NAME: string;
  GMAIL_PUBSUB_PUSH_AUDIENCE: string;
  GMAIL_PUBSUB_PUSH_SERVICE_ACCOUNT: string;
  AXIOM_API_TOKEN: string;
  AXIOM_DATASET: string;
  THREADS_BUCKET: R2Bucket;
  DEV_PROXY: string;
  MEET_AUTH_HEADER: string;
  MEET_API_URL: string;
  ENABLE_MEET: 'true' | 'false';
  OTEL_EXPORTER_OTLP_ENDPOINT?: string;
  OTEL_EXPORTER_OTLP_HEADERS?: string;
  OTEL_SERVICE_NAME?: string;
};

const env = _env as unknown as ZeroEnv;
export { env };
