export type ZeroEnv = {
  NODE_ENV: 'local' | 'development' | 'production';
  ZERO_LOG_LEVEL?: 'silent' | 'error' | 'warn' | 'info' | 'debug';
  JWT_SECRET: string;
  BASE_URL: string;
  VITE_PUBLIC_APP_URL: string;
  DATABASE_URL: string;
  CREDENTIAL_ENCRYPTION_KEY: string;
  NANGO_BASE_URL?: string;
  NANGO_SECRET_KEY?: string;
  NANGO_GMAIL_INTEGRATION_KEY?: string;
  NANGO_OUTLOOK_INTEGRATION_KEY?: string;
  NANGO_ZOHO_MAIL_INTEGRATION_KEY?: string;
  NANGO_IMAP_SMTP_INTEGRATION_KEY?: string;
  MAIL_PROTOCOL_ALLOWED_HOSTS?: string;
  INTEGRATION_API_TOKEN?: string;
  MAIL_WEBHOOK_ENABLED?: 'true' | 'false';
  MAIL_WEBHOOK_URL?: string;
  BETTER_AUTH_SECRET: string;
  RESEND_API_KEY: string;
  COOKIE_DOMAIN: string;
  BETTER_AUTH_TRUSTED_ORIGINS: string;
  ZERO_ADMIN_AUTO_PROVISION?: 'true' | 'false';
  ZERO_ADMIN_NAME?: string;
  ZERO_ADMIN_EMAIL?: string;
  ZERO_ADMIN_PASSWORD?: string;
  ZERO_ADMIN_BOOTSTRAP_SECRET?: string;
  GITHUB_CLIENT_ID: string;
  GITHUB_CLIENT_SECRET: string;
  VITE_PUBLIC_BACKEND_URL: string;
  MEET_AUTH_HEADER: string;
  MEET_API_URL: string;
  ENABLE_MEET: 'true' | 'false';
};

const env = process.env as unknown as ZeroEnv;
export { env };
