import { paraglideVitePlugin } from '@inlang/paraglide-js';
import { reactRouter } from '@react-router/dev/vite';
import tsconfigPaths from 'vite-tsconfig-paths';
import oxlintPlugin from 'vite-plugin-oxlint';
import tailwindcss from '@tailwindcss/vite';
import babel from 'vite-plugin-babel';
import { defineConfig } from 'vite';
import dedent from 'dedent';

const ReactCompilerConfig = {
  /* ... */
};

const reactCompilerPlugins =
  process.env.ZERO_DOCKER_DEV === 'true'
    ? []
    : [
        babel({
          filter: /\.[jt]sx?$/,
          babelConfig: {
            presets: ['@babel/preset-typescript'],
            plugins: [['babel-plugin-react-compiler', ReactCompilerConfig]],
          },
        }),
      ];

export default defineConfig(({ command }) => ({
  plugins: [
    ...(command === 'serve' ? [oxlintPlugin()] : []),
    reactRouter(),
    ...reactCompilerPlugins,
    tsconfigPaths(),
    tailwindcss(),
    {
      name: 'add-headers',
      applyToEnvironment: (env) => env.name === 'client',
      generateBundle() {
        this.emitFile({
          fileName: '_headers',
          type: 'asset',
          source: dedent`
            # Autogenerated

            /assets/*
              ! Cache-Control
                Cache-Control: public, immutable, max-age=31536000
          `,
        });
      },
    },
    paraglideVitePlugin({
      project: './project.inlang',
      outdir: './paraglide',
      strategy: ['cookie', 'baseLocale'],
    }),
  ],
  server: {
    port: 3000,
    warmup: {
      clientFiles: ['./app/**/*', './components/**/*'],
    },
  },
  //   ssr: {
  //     optimizeDeps: {
  //       include: ['novel', '@tiptap/extension-placeholder'],
  //     },
  //   },
  esbuild: {
    pure: ['console.log'],
  },
  build: {
    sourcemap: false,
  },
  resolve: {
    alias: {
      tslib: 'tslib/tslib.es6.js',
    },
  },
}));
